*** src/testdir/Makefile	2011-07-15 21:16:54.000000000 +0200
--- Makefile	2011-10-12 17:39:03.000000000 +0200
***************
*** 26,32 ****
  		test64.out test65.out test66.out test67.out test68.out \
  		test69.out test70.out test71.out test72.out test73.out \
  		test74.out test75.out test76.out test77.out test78.out \
! 		test79.out test80.out test81.out test82.out
  
  SCRIPTS_GUI = test16.out
  
--- 26,32 ----
  		test64.out test65.out test66.out test67.out test68.out \
  		test69.out test70.out test71.out test72.out test73.out \
  		test74.out test75.out test76.out test77.out test78.out \
! 		test79.out test80.out test81.out test82.out test83.out
  
  SCRIPTS_GUI = test16.out
  
***************
*** 72,78 ****
  		  fi \
  		else echo $* NO OUTPUT >>test.log; \
  		fi"
! 	-rm -rf X* test.ok viminfo
  
  test49.out: test49.vim
  
--- 72,78 ----
  		  fi \
  		else echo $* NO OUTPUT >>test.log; \
  		fi"
! #	-rm -rf X* test.ok viminfo
  
  test49.out: test49.vim
  
