*** src/po/Makefile	2013-01-30 12:50:50.000000000 +0100
--- Makefile	2013-04-27 14:04:45.000000000 +0200
***************
*** 176,184 ****
  
  converted: $(MOCONVERTED)
  
! # nl.po was added later, if it does not exist use an empty file.
  nl.po:
! 	touch nl.po
  
  # Norwegian/Bokmal: "nb" is an alias for "no".
  # Copying the file is not efficient, but I don't know of another way to make
--- 176,185 ----
  
  converted: $(MOCONVERTED)
  
! # nl.po was added later, if it does not exist use a file with just a # in it
! # (an empty file doesn't work with old msgfmt).
  nl.po:
! 	@( echo \# > nl.po )
  
  # Norwegian/Bokmal: "nb" is an alias for "no".
  # Copying the file is not efficient, but I don't know of another way to make
